on:
  push:
    tags:
      - '*'

jobs:
  push_img:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          PIP_PACKAGES=$(echo "$GITHUB_REF_NAME" | sed "s/,/ /g; s/=/==/g")
          DOCKER_IMG_TAG=$(echo "$GITHUB_REF_NAME" | sed "s/,/-/g; s/=/-/g")
          echo "PIP_PACKAGES=$PIP_PACKAGES" >> $GITHUB_ENV
          echo "DOCKER_IMG_TAG=$DOCKER_IMG_TAG" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.DOCKER_IMG_TAG }}
          build-args: |
            "PIP_PACKAGES=${{ env.PIP_PACKAGES }}"
